# Generated by Django 4.2.7 on 2023-11-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default_YS9Vr6e.png', null=True, upload_to='profiles/'),
        ),
    ]
